# view_location: [3, -8, 2] # rolling
view_location: [0, -1, 0] # camera
ortho_scale: 3.2
# view_rotation: [1.2566370614359172, 0, 1.0471975511965976] # rolling
view_rotation: [1.5707963267948966, 0, 0] # camera
view_distance: 0 # camera
light_position: [0.5, -0.5, 0.25]
# light_position: [1, -3, 3]
light_rotation: [1.2, 0, 0.39269908169872414]
# light_rotation: [0.5, 0.3, 0]
light_energy: 4.0
renderer: "BLENDER_EEVEE"